version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    networks:
      - app-network
    depends_on:
      - postgres
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: your_postgres_user
      DB_PASSWORD: your_postgres_password
      DB_DATABASE: your_postgres_db

  desktop:
    build:
      context: .
      dockerfile: desktop.Dockerfile
    networks:
      - app-network

  mobile:
    build:
      context: .
      dockerfile: mobile.Dockerfile
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx-compose.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - desktop
      - mobile
    networks:
      - app-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: your_postgres_user
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_DB: your_postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
