services:
  api:
    image: 574099924710.dkr.ecr.eu-central-1.amazonaws.com/attendance-taker-api:latest
    networks:
      - app-network
    depends_on:
      - postgres
      - redis
    env_file: .env

  desktop:
    image: 574099924710.dkr.ecr.eu-central-1.amazonaws.com/attendance-taker-desktop:latest
    networks:
      - app-network

  mobile:
    image: 574099924710.dkr.ecr.eu-central-1.amazonaws.com/attendance-taker-mobile:latest
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx-compose.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - desktop
      - mobile
    networks:
      - app-network

  postgres:
    image: postgres:13
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    networks:
      - app-network
    volumes:
      - redis_data:/data

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
